---
title: "Lists - In Class Exercises"
author: "Lauren Duvall"
date: "DATA 2401"
output: html_document

---

# Exercises: 

Make a list that contains the information on a single playing card. Suit, face, and value. 

```{r}
one_card <-list (
  suit='hearts',
  face='queen',
  value= 10
)
one_card
```


Make a second list where each element contains all the options for suit, face, and value, respectively. 

```{r}
all_cards <- list (
  suits= c('hearts','diamonds','spades', 'clubs'),
  face= c(1:10, 'jack','queen','king'),
  value= c(1:10,10,10,10)
)
all_cards
```


If `Newlist <- list(a=1:10, b="Good morning", c="Hi")`, write an R statement that will add 1 to each element of the first vector in Newlist.

```{r}
Newlist <- list(a=1:10, b="Good morning", c="Hi")
Newlist[[1]] + 1

```

If `b <- list(a=1:10, c="Hello", d="AA")`, write an R expression that will get all elements of the first vector of b, except the second, and write another that returns only elements of `a` that are greater than 7.

```{r}
b <- list(a=1:10, c="Hello", d="AA")
b$a[-2]
b$a[b$a>7]
```

Let `x <- list(a=5:10, c="Hello", d="AA")`, write an R statement to add a new item z = "NewItem" to the list x.

```{r}
x <- list(a=5:10, c="Hello", d="AA")
x$z<-'NewItem'
x
```
